2014-04-24 05:47:15 Error: [MissingControllerException] Controller class EditMessage.phpController could not be found.
Exception Attributes: array (
  'class' => 'EditMessage.phpController',
  'plugin' => NULL,
)
Request URL: /edit_message.php?id=1&mid=19
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-24 07:24:49 Error: Fatal Error (4): syntax error, unexpected '}' in [/vagrant/data/Test/myapp/Controller/PostsController.php, line 29]
2014-04-24 07:24:49 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 29)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 29, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 29, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-24 07:25:16 Error: Fatal Error (4): syntax error, unexpected T_STRING in [/vagrant/data/Test/myapp/Controller/PostsController.php, line 33]
2014-04-24 07:25:16 Error: [FatalErrorException] syntax error, unexpected T_STRING
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 33)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 33, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 33, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 01:24:08 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Can\'t connect to local MySQL server through socket \'/var/lib/mysql/mysql.sock\' (111)',
  'enabled' => true,
)
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('default')
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1126): Model->setDataSource('default')
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /vagrant/data/Test/myapp/Controller/PostsController.php(37): Model->find('all')
#8 [internal function]: PostsController->index()
#9 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#10 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#12 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-04-25 03:27:50 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(37): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-25 03:28:49 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(37): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-25 03:28:58 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/index
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-25 03:31:23 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/index
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-25 03:31:25 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/index
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-25 07:03:46 Error: Fatal Error (4): syntax error, unexpected ')' in [/vagrant/data/Test/myapp/View/Users/index.ctp, line 7]
2014-04-25 07:03:46 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 7)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 7, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 7, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:01:52 Error: Fatal Error (4): syntax error, unexpected T_OBJECT_OPERATOR in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 14]
2014-04-25 08:01:52 Error: [FatalErrorException] syntax error, unexpected T_OBJECT_OPERATOR
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 14)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:02:42 Error: Fatal Error (4): syntax error, unexpected T_OBJECT_OPERATOR in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 14]
2014-04-25 08:02:42 Error: [FatalErrorException] syntax error, unexpected T_OBJECT_OPERATOR
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 14)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:03:04 Error: Fatal Error (4): syntax error, unexpected T_OBJECT_OPERATOR in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 14]
2014-04-25 08:03:04 Error: [FatalErrorException] syntax error, unexpected T_OBJECT_OPERATOR
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 14)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:04:55 Error: Fatal Error (4): syntax error, unexpected T_OBJECT_OPERATOR in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 14]
2014-04-25 08:04:55 Error: [FatalErrorException] syntax error, unexpected T_OBJECT_OPERATOR
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 14)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:04:59 Error: Fatal Error (4): syntax error, unexpected T_OBJECT_OPERATOR in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 14]
2014-04-25 08:04:59 Error: [FatalErrorException] syntax error, unexpected T_OBJECT_OPERATOR
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 14)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 14, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:06:34 Error: Fatal Error (4): syntax error, unexpected T_OBJECT_OPERATOR in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 18]
2014-04-25 08:06:34 Error: [FatalErrorException] syntax error, unexpected T_OBJECT_OPERATOR
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:06:37 Error: Fatal Error (4): syntax error, unexpected T_OBJECT_OPERATOR in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 18]
2014-04-25 08:06:37 Error: [FatalErrorException] syntax error, unexpected T_OBJECT_OPERATOR
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:07:08 Error: Fatal Error (4): syntax error, unexpected '<' in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 18]
2014-04-25 08:07:08 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:07:15 Error: Fatal Error (4): syntax error, unexpected '<' in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 18]
2014-04-25 08:07:15 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:24:56 Error: Fatal Error (4): syntax error, unexpected '<' in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 18]
2014-04-25 08:24:56 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:25:15 Error: Fatal Error (4): syntax error, unexpected '(', expecting T_STRING or T_VARIABLE or '{' or '$' in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 18]
2014-04-25 08:25:15 Error: [FatalErrorException] syntax error, unexpected '(', expecting T_STRING or T_VARIABLE or '{' or '$'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:25:41 Error: Fatal Error (4): syntax error, unexpected '(', expecting T_STRING or T_VARIABLE or '{' or '$' in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 18]
2014-04-25 08:25:41 Error: [FatalErrorException] syntax error, unexpected '(', expecting T_STRING or T_VARIABLE or '{' or '$'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 18, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:26:19 Error: [MissingComponentException] Component class SesssionComponent could not be found.
Exception Attributes: array (
  'class' => 'SesssionComponent',
  'plugin' => false,
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('Sesssion', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 08:28:33 Error: Fatal Error (4): syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting ',' or ';' in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 4]
2014-04-25 08:28:33 Error: [FatalErrorException] syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting ',' or ';'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 4, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 4, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:28:55 Error: [MissingComponentException] Component class SesssionComponent could not be found.
Exception Attributes: array (
  'class' => 'SesssionComponent',
  'plugin' => false,
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('Sesssion', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 08:32:12 Error: [MissingComponentException] Component class SesssionComponent could not be found.
Exception Attributes: array (
  'class' => 'SesssionComponent',
  'plugin' => false,
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('Sesssion', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 08:32:14 Error: [MissingComponentException] Component class SesssionComponent could not be found.
Exception Attributes: array (
  'class' => 'SesssionComponent',
  'plugin' => false,
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('Sesssion', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 08:32:34 Error: [MissingComponentException] Component class SesssionComponent could not be found.
Exception Attributes: array (
  'class' => 'SesssionComponent',
  'plugin' => false,
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('Sesssion', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 08:34:33 Error: [MissingComponentException] Component class SesssionComponent could not be found.
Exception Attributes: array (
  'class' => 'SesssionComponent',
  'plugin' => false,
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('Sesssion', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 08:34:34 Error: [MissingComponentException] Component class SesssionComponent could not be found.
Exception Attributes: array (
  'class' => 'SesssionComponent',
  'plugin' => false,
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('Sesssion', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 08:50:04 Error: [MissingComponentException] Component class SesssionComponent could not be found.
Exception Attributes: array (
  'class' => 'SesssionComponent',
  'plugin' => false,
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('Sesssion', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 08:50:11 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [/vagrant/data/Test/myapp/Model/User.php, line 20]
2014-04-25 08:50:11 Error: [FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 20, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 20, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:52:42 Error: Fatal Error (4): syntax error, unexpected T_PUBLIC, expecting ',' or ';' in [/vagrant/data/Test/myapp/Model/User.php, line 20]
2014-04-25 08:52:42 Error: [FatalErrorException] syntax error, unexpected T_PUBLIC, expecting ',' or ';'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 20, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 20, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:52:47 Error: Fatal Error (4): syntax error, unexpected T_PUBLIC, expecting ',' or ';' in [/vagrant/data/Test/myapp/Model/User.php, line 20]
2014-04-25 08:52:47 Error: [FatalErrorException] syntax error, unexpected T_PUBLIC, expecting ',' or ';'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 20, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 20, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:53:03 Error: Fatal Error (4): syntax error, unexpected T_PUBLIC, expecting ',' or ';' in [/vagrant/data/Test/myapp/Model/User.php, line 21]
2014-04-25 08:53:03 Error: [FatalErrorException] syntax error, unexpected T_PUBLIC, expecting ',' or ';'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 21, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 21, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:56:28 Error: Fatal Error (4): syntax error, unexpected T_PUBLIC, expecting ',' or ';' in [/vagrant/data/Test/myapp/Model/User.php, line 21]
2014-04-25 08:56:28 Error: [FatalErrorException] syntax error, unexpected T_PUBLIC, expecting ',' or ';'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 21, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 21, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:56:32 Error: Fatal Error (4): syntax error, unexpected T_PUBLIC, expecting ',' or ';' in [/vagrant/data/Test/myapp/Model/User.php, line 21]
2014-04-25 08:56:32 Error: [FatalErrorException] syntax error, unexpected T_PUBLIC, expecting ',' or ';'
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 21, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 21, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:57:20 Error: Fatal Error (1): Call to undefined method SessionComponent::setFlash() in [/vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Component/AuthComponent.php, line 826]
2014-04-25 08:57:20 Error: [FatalErrorException] Call to undefined method SessionComponent::setFlash()
Request URL: /users/signup
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/vagrant/data/T...', 826)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:58:59 Error: Fatal Error (1): Call to undefined method SessionComponent::setFlash() in [/vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Component/AuthComponent.php, line 826]
2014-04-25 08:58:59 Error: [FatalErrorException] Call to undefined method SessionComponent::setFlash()
Request URL: /users/signup
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/vagrant/data/T...', 826)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 08:59:05 Error: Fatal Error (1): Call to undefined method SessionComponent::setFlash() in [/vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Component/AuthComponent.php, line 826]
2014-04-25 08:59:05 Error: [FatalErrorException] Call to undefined method SessionComponent::setFlash()
Request URL: /users/signup
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/vagrant/data/T...', 826)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 09:04:47 Error: Fatal Error (1): Call to undefined method SessionComponent::setFlash() in [/vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Component/AuthComponent.php, line 826]
2014-04-25 09:04:47 Error: [FatalErrorException] Call to undefined method SessionComponent::setFlash()
Request URL: /users/signup
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/vagrant/data/T...', 826)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 09:06:05 Error: Fatal Error (1): Call to undefined method SessionComponent::setFlash() in [/vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Component/AuthComponent.php, line 826]
2014-04-25 09:06:05 Error: [FatalErrorException] Call to undefined method SessionComponent::setFlash()
Request URL: /users/signup
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/vagrant/data/T...', 826)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 09:06:08 Error: Fatal Error (1): Call to undefined method SessionComponent::setFlash() in [/vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Component/AuthComponent.php, line 826]
2014-04-25 09:06:08 Error: [FatalErrorException] Call to undefined method SessionComponent::setFlash()
Request URL: /users/signup
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/vagrant/data/T...', 826)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/vagrant/data/T...', 826, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-25 09:07:57 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Users/login.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Users/login.ctp',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 09:08:02 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Users/login.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Users/login.ctp',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 09:08:19 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Users/login.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Users/login.ctp',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-25 09:09:01 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:09:15 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:10:45 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:10:48 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:10:55 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:11:49 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:12:32 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:12:41 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:13:17 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:13:25 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:13:26 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:13:54 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:14:29 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-25 09:14:34 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-26 01:27:12 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 8]
2014-04-26 01:27:12 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 8, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 8, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-26 01:27:19 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 8]
2014-04-26 01:27:19 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 8, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 8, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-26 04:31:44 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(37): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-26 04:32:53 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(28): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-26 04:32:57 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(28): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-26 04:34:08 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [/vagrant/data/Test/myapp/Model/Post.php, line 28]
2014-04-26 04:34:08 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 28)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 28, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 28, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-26 07:58:03 Error: Fatal Error (4): syntax error, unexpected T_PUBLIC in [/vagrant/data/Test/myapp/Controller/PostsController.php, line 74]
2014-04-26 07:58:03 Error: [FatalErrorException] syntax error, unexpected T_PUBLIC
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 74)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 74, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 74, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-26 09:11:49 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Users/login.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Users/login.ctp',
)
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-26 09:12:57 Error: Fatal Error (1): Call to a member function login() on a non-object in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 17]
2014-04-26 09:12:57 Error: [FatalErrorException] Call to a member function login() on a non-object
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 17, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 17, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-26 09:13:22 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Users/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Users/index.ctp',
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-26 09:14:05 Error: [MissingActionException] Action UsersController::index() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'index',
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-26 09:15:09 Error: Fatal Error (1): Call to a member function login() on a non-object in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 17]
2014-04-26 09:15:09 Error: [FatalErrorException] Call to a member function login() on a non-object
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 17, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 17, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-26 09:41:32 Error: Fatal Error (1): Class 'SimplePasswordHasher' not found in [/vagrant/data/Test/myapp/Model/User.php, line 23]
2014-04-26 09:41:32 Error: [FatalErrorException] Class 'SimplePasswordHasher' not found
Request URL: /users/signup
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'SimplePa...', '/vagrant/data/T...', 23)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'SimplePa...', '/vagrant/data/T...', 23, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Class 'SimplePa...', '/vagrant/data/T...', 23, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-26 09:42:19 Error: [MissingActionException] Action UsersController::index() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'index',
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-26 09:43:23 Error: [MissingActionException] Action UsersController::index() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'index',
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-26 09:53:34 Error: Fatal Error (1): Call to a member function login() on a non-object in [/vagrant/data/Test/myapp/Controller/UsersController.php, line 17]
2014-04-26 09:53:34 Error: [FatalErrorException] Call to a member function login() on a non-object
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 17, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 17, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-28 01:48:35 Error: Fatal Error (4): syntax error, unexpected '/', expecting T_FUNCTION in [/vagrant/data/Test/myapp/Controller/AppController.php, line 3]
2014-04-28 01:48:35 Error: [FatalErrorException] syntax error, unexpected '/', expecting T_FUNCTION
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 3, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 3, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-28 01:57:34 Error: [MissingActionException] Action UsersController::index() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'index',
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-28 01:57:44 Error: [MissingActionException] Action UsersController::index() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'index',
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-28 04:08:00 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [/vagrant/data/Test/myapp/Model/User.php, line 28]
2014-04-28 04:08:00 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 28)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 28, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 28, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-28 07:30:01 Error: Fatal Error (4): syntax error, unexpected '<' in [/vagrant/data/Test/myapp/View/Layouts/logout.ctp, line 9]
2014-04-28 07:30:01 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 9)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 9, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 9, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-28 07:30:29 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [/vagrant/data/Test/myapp/View/Layouts/logout.ctp, line 6]
2014-04-28 07:30:29 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 6)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 6, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 6, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-28 07:49:33 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Users/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Users/index.ctp',
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-28 08:00:03 Error: [MissingActionException] Action PostsController::logout() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'logout',
)
Request URL: /posts/logout
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-28 08:00:36 Error: [MissingActionException] Action PostsController::logout() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'logout',
)
Request URL: /posts/logout
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-28 08:00:40 Error: [MissingActionException] Action PostsController::logout() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'logout',
)
Request URL: /posts/logout
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-28 08:00:43 Error: [MissingActionException] Action PostsController::logout() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'logout',
)
Request URL: /posts/logout
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-28 08:58:02 Error: [MissingComponentException] Component class authorizeComponent could not be found.
Exception Attributes: array (
  'class' => 'authorizeComponent',
  'plugin' => false,
)
Request URL: /users/login/home
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authorize', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-28 09:02:26 Error: [MissingComponentException] Component class authorizeComponent could not be found.
Exception Attributes: array (
  'class' => 'authorizeComponent',
  'plugin' => false,
)
Request URL: /users/login/home
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authorize', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-28 09:02:31 Error: [MissingComponentException] Component class authorizeComponent could not be found.
Exception Attributes: array (
  'class' => 'authorizeComponent',
  'plugin' => false,
)
Request URL: /users/login/
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authorize', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-28 09:03:18 Error: [MissingComponentException] Component class authorizeComponent could not be found.
Exception Attributes: array (
  'class' => 'authorizeComponent',
  'plugin' => false,
)
Request URL: /posts/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authorize', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostsController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-28 09:06:32 Error: [MissingComponentException] Component class authorizeComponent could not be found.
Exception Attributes: array (
  'class' => 'authorizeComponent',
  'plugin' => false,
)
Request URL: /users/login/home
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authorize', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-28 11:09:12 Error: [MissingComponentException] Component class authorizeComponent could not be found.
Exception Attributes: array (
  'class' => 'authorizeComponent',
  'plugin' => false,
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authorize', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostsController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-28 11:09:22 Error: [MissingComponentException] Component class authorizeComponent could not be found.
Exception Attributes: array (
  'class' => 'authorizeComponent',
  'plugin' => false,
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authorize', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostsController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-28 11:09:25 Error: [MissingComponentException] Component class authorizeComponent could not be found.
Exception Attributes: array (
  'class' => 'authorizeComponent',
  'plugin' => false,
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authorize', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostsController))
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(181): Controller->constructClasses()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 01:34:19 Error: Fatal Error (4): syntax error, unexpected '[', expecting ']' in [/vagrant/data/Test/myapp/View/Posts/index.ctp, line 25]
2014-04-29 01:34:19 Error: [FatalErrorException] syntax error, unexpected '[', expecting ']'
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 25, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 25, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 01:34:52 Error: Fatal Error (4): syntax error, unexpected '[', expecting ']' in [/vagrant/data/Test/myapp/View/Posts/index.ctp, line 25]
2014-04-29 01:34:52 Error: [FatalErrorException] syntax error, unexpected '[', expecting ']'
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 25, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 25, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 01:34:57 Error: Fatal Error (4): syntax error, unexpected '[', expecting ']' in [/vagrant/data/Test/myapp/View/Posts/index.ctp, line 25]
2014-04-29 01:34:57 Error: [FatalErrorException] syntax error, unexpected '[', expecting ']'
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 25, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 25, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 01:35:17 Error: [MissingHelperException] Helper class AuthHelper could not be found.
Exception Attributes: array (
  'class' => 'AuthHelper',
  'plugin' => false,
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/HelperCollection.php(63): HelperCollection->load('Auth')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(824): HelperCollection->__isset('Auth')
#2 /vagrant/data/Test/myapp/View/Posts/index.ctp(25): View->__get('Auth')
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(935): include('/vagrant/data/T...')
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(897): View->_evaluate('/vagrant/data/T...', Array)
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(466): View->_render('/vagrant/data/T...')
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#8 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#9 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-04-29 03:15:59 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-29 03:16:05 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-29 03:16:09 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-29 03:16:26 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts/add
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1355): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(207): Model->schema()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Post', 'fields')
#4 /vagrant/data/Test/myapp/View/Posts/add.ctp(3): FormHelper->create('Post')
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(935): include('/vagrant/data/T...')
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(897): View->_evaluate('/vagrant/data/T...', Array)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(466): View->_render('/vagrant/data/T...')
#8 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#9 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#10 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-29 03:16:27 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-29 03:16:34 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Users/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Users/index.ctp',
)
Request URL: /users
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 03:16:39 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-29 03:17:12 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[42000] [1049] Unknown database \'Test_Cake\'',
  'enabled' => true,
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('default')
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1126): Model->setDataSource('default')
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#8 [internal function]: PostsController->index()
#9 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#10 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#12 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-04-29 03:29:54 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-29 03:32:03 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-29 03:32:08 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-29 03:32:10 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-29 03:32:25 Error: Fatal Error (4): syntax error, unexpected $end, expecting T_FUNCTION in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 104]
2014-04-29 03:32:25 Error: [FatalErrorException] syntax error, unexpected $end, expecting T_FUNCTION
Request URL: /threads/index
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 104)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 104, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 104, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 03:33:09 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /threads/add
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1355): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(207): Model->schema()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Post', 'fields')
#4 /vagrant/data/Test/myapp/View/Threads/add.ctp(3): FormHelper->create('Post')
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(935): include('/vagrant/data/T...')
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(897): View->_evaluate('/vagrant/data/T...', Array)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(466): View->_render('/vagrant/data/T...')
#8 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#9 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#10 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#11 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-29 03:34:13 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /threads/add
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1355): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(207): Model->schema()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Post', 'fields')
#4 /vagrant/data/Test/myapp/View/Threads/add.ctp(3): FormHelper->create('Post')
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(935): include('/vagrant/data/T...')
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(897): View->_evaluate('/vagrant/data/T...', Array)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(466): View->_render('/vagrant/data/T...')
#8 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#9 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#10 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#11 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-29 03:38:41 Error: Fatal Error (1): Call to undefined function findById() in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 38]
2014-04-29 03:38:41 Error: [FatalErrorException] Call to undefined function findById()
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/vagrant/data/T...', 38)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/vagrant/data/T...', 38, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/vagrant/data/T...', 38, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 03:45:30 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Threads/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Threads/index.ctp',
)
Request URL: /threads
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 04:08:20 Error: Fatal Error (1): Call to undefined function findById() in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 38]
2014-04-29 04:08:20 Error: [FatalErrorException] Call to undefined function findById()
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/vagrant/data/T...', 38)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/vagrant/data/T...', 38, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/vagrant/data/T...', 38, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 06:28:42 Error: Fatal Error (1): Call to a member function findAllbyThreadId() on a non-object in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 42]
2014-04-29 06:28:42 Error: [FatalErrorException] Call to a member function findAllbyThreadId() on a non-object
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 42)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 42, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 42, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 06:45:18 Error: Fatal Error (1): Call to a member function findAllByThreadId() on a non-object in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 42]
2014-04-29 06:45:18 Error: [FatalErrorException] Call to a member function findAllByThreadId() on a non-object
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 42)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 42, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 42, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 06:45:22 Error: Fatal Error (1): Call to a member function findAllByThreadId() on a non-object in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 42]
2014-04-29 06:45:22 Error: [FatalErrorException] Call to a member function findAllByThreadId() on a non-object
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 42)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 42, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 42, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 07:54:28 Error: Fatal Error (4): syntax error, unexpected '&' in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 42]
2014-04-29 07:54:28 Error: [FatalErrorException] syntax error, unexpected '&'
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 42)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 42, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 42, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 07:54:58 Error: Fatal Error (1): Call to a member function findAllByThreadId() on a non-object in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 43]
2014-04-29 07:54:58 Error: [FatalErrorException] Call to a member function findAllByThreadId() on a non-object
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 43)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 43, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 43, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 07:55:15 Error: Fatal Error (4): syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting ')' in [/vagrant/data/Test/myapp/View/Threads/view.ctp, line 33]
2014-04-29 07:55:15 Error: [FatalErrorException] syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting ')'
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 33)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 33, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 33, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 07:56:47 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Messages/add.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Messages/add.ctp',
)
Request URL: /messages/add
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 07:59:14 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Messages/add.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Messages/add.ctp',
)
Request URL: /messages/add
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 08:18:27 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /messages/add/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1355): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(207): Model->schema()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Post', 'fields')
#4 /vagrant/data/Test/myapp/View/Messages/add.ctp(3): FormHelper->create('Post')
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(935): include('/vagrant/data/T...')
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(897): View->_evaluate('/vagrant/data/T...', Array)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(466): View->_render('/vagrant/data/T...')
#8 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#9 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#10 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#11 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-29 08:21:20 Error: Fatal Error (4): syntax error, unexpected T_DOUBLE_ARROW in [/vagrant/data/Test/myapp/View/Threads/view.ctp, line 44]
2014-04-29 08:21:20 Error: [FatalErrorException] syntax error, unexpected T_DOUBLE_ARROW
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 44)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 44, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 44, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 08:27:37 Error: Fatal Error (1): Call to a member function save() on a non-object in [/vagrant/data/Test/myapp/Controller/MessagesController.php, line 51]
2014-04-29 08:27:37 Error: [FatalErrorException] Call to a member function save() on a non-object
Request URL: /messages/add/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 51, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 51, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 08:28:07 Error: [NotFoundException] Invalid thread
Request URL: /threads/view
Stack Trace:
#0 [internal function]: ThreadsController->view()
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 08:29:39 Error: [NotFoundException] Invalid thread
Request URL: /threads/view
Stack Trace:
#0 [internal function]: ThreadsController->view()
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 08:38:40 Error: [MissingActionException] Action MessagesController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'MessagesController',
  'action' => 'edit',
)
Request URL: /messages/edit/7
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-29 08:38:48 Error: [MissingActionException] Action MessagesController::index() could not be found.
Exception Attributes: array (
  'controller' => 'MessagesController',
  'action' => 'index',
)
Request URL: /messages/
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#2 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-29 08:59:51 Error: [NotFoundException] Invalid thread
Request URL: /threads/view
Stack Trace:
#0 [internal function]: ThreadsController->view()
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 09:00:23 Error: [NotFoundException] Invalid thread
Request URL: /threads/view
Stack Trace:
#0 [internal function]: ThreadsController->view()
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 09:25:24 Error: Fatal Error (4): syntax error, unexpected T_OBJECT_OPERATOR, expecting ')' in [/vagrant/data/Test/myapp/Controller/MessagesController.php, line 70]
2014-04-29 09:25:24 Error: [FatalErrorException] syntax error, unexpected T_OBJECT_OPERATOR, expecting ')'
Request URL: /messages/delete/7
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 70)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 70, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 70, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 09:25:53 Error: Fatal Error (4): syntax error, unexpected '*', expecting T_FUNCTION in [/vagrant/data/Test/myapp/Controller/MessagesController.php, line 103]
2014-04-29 09:25:53 Error: [FatalErrorException] syntax error, unexpected '*', expecting T_FUNCTION
Request URL: /messages/delete/7
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 103)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 103, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 103, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 09:26:17 Error: [NotFoundException] Invalid thread
Request URL: /threads/view
Stack Trace:
#0 [internal function]: ThreadsController->view()
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 09:27:03 Error: [NotFoundException] Invalid thread
Request URL: /threads/view
Stack Trace:
#0 [internal function]: ThreadsController->view()
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 09:27:09 Error: [NotFoundException] Invalid thread
Request URL: /threads/view/8
Stack Trace:
#0 [internal function]: ThreadsController->view('8')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 09:27:56 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /messages/edit/10
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1355): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(207): Model->schema()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Post', 'fields')
#4 /vagrant/data/Test/myapp/View/Messages/edit.ctp(3): FormHelper->create('Post')
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(935): include('/vagrant/data/T...')
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(897): View->_evaluate('/vagrant/data/T...', Array)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(466): View->_render('/vagrant/data/T...')
#8 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#9 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#10 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#11 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-29 09:29:15 Error: [MissingViewException] View file "/vagrant/data/Test/myapp/View/Threads/view.ctp" is missing.
Exception Attributes: array (
  'file' => '/vagrant/data/Test/myapp/View/Threads/view.ctp',
)
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(463): View->_getViewFileName(NULL)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#4 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-29 10:44:51 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.' in 'where clause'
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(665): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): DboSource->read(Object(User), Array)
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(592): Model->find('all', Array)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(800): DboSource->query('findAllBy', Array, Object(User))
#8 /vagrant/data/Test/myapp/Controller/ThreadsController.php(44): Model->__call('findAllBy', Array)
#9 /vagrant/data/Test/myapp/Controller/ThreadsController.php(44): User->findAllBy('1')
#10 [internal function]: ThreadsController->view('1')
#11 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#12 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#13 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#14 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-04-29 11:06:13 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.' in 'where clause'
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(665): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): DboSource->read(Object(User), Array)
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(592): Model->find('all', Array)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(800): DboSource->query('findAllBy', Array, Object(User))
#8 /vagrant/data/Test/myapp/Controller/ThreadsController.php(44): Model->__call('findAllBy', Array)
#9 /vagrant/data/Test/myapp/Controller/ThreadsController.php(44): User->findAllBy('1')
#10 [internal function]: ThreadsController->view('1')
#11 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#12 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#13 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#14 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-04-29 11:06:15 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.' in 'where clause'
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(665): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): DboSource->read(Object(User), Array)
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(592): Model->find('all', Array)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(800): DboSource->query('findAllBy', Array, Object(User))
#8 /vagrant/data/Test/myapp/Controller/ThreadsController.php(44): Model->__call('findAllBy', Array)
#9 /vagrant/data/Test/myapp/Controller/ThreadsController.php(44): User->findAllBy('1')
#10 [internal function]: ThreadsController->view('1')
#11 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#12 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#13 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#14 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-04-29 11:09:12 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.' in 'where clause'
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(665): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): DboSource->read(Object(User), Array)
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(592): Model->find('all', Array)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(800): DboSource->query('findAllBy', Array, Object(User))
#8 /vagrant/data/Test/myapp/Controller/ThreadsController.php(44): Model->__call('findAllBy', Array)
#9 /vagrant/data/Test/myapp/Controller/ThreadsController.php(44): User->findAllBy('1')
#10 [internal function]: ThreadsController->view('1')
#11 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#12 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#13 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#14 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-04-29 11:11:50 Error: Fatal Error (4): syntax error, unexpected T_VARIABLE in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 45]
2014-04-29 11:11:50 Error: [FatalErrorException] syntax error, unexpected T_VARIABLE
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 45)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 45, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 45, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-29 11:17:50 Error: Fatal Error (4): syntax error, unexpected T_VARIABLE in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 46]
2014-04-29 11:17:50 Error: [FatalErrorException] syntax error, unexpected T_VARIABLE
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 46)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 46, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 46, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-05 06:40:51 Error: Fatal Error (4): syntax error, unexpected '}' in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 60]
2014-05-05 06:40:51 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/vagrant/data/T...', 60)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/vagrant/data/T...', 60, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/vagrant/data/T...', 60, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-05 06:41:04 Error: Fatal Error (1): Call to a member function remoteFunction() on a non-object in [/vagrant/data/Test/myapp/Controller/ThreadsController.php, line 59]
2014-05-05 06:41:04 Error: [FatalErrorException] Call to a member function remoteFunction() on a non-object
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 59)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 59, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 59, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-05 06:42:57 Error: [MissingHelperException] Helper class AjaxHelper could not be found.
Exception Attributes: array (
  'class' => 'AjaxHelper',
  'plugin' => false,
)
Request URL: /threads/view/1
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/HelperCollection.php(63): HelperCollection->load('Ajax')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(824): HelperCollection->__isset('Ajax')
#2 /vagrant/data/Test/myapp/View/Threads/view.ctp(44): View->__get('Ajax')
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(935): include('/vagrant/data/T...')
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(897): View->_evaluate('/vagrant/data/T...', Array)
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(466): View->_render('/vagrant/data/T...')
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#8 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#9 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-05-05 06:55:25 Error: [MissingHelperException] Helper class JavascriptHelper could not be found.
Exception Attributes: array (
  'class' => 'JavascriptHelper',
  'plugin' => false,
)
Request URL: /threads
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(873): HelperCollection->load('Javascript', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(347): View->loadHelpers()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(1241): View->__construct(Object(ThreadsController))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(940): Controller->_getViewObject()
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest), Object(CakeResponse))
#6 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-05-05 06:59:10 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-05-05 06:59:19 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /posts
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3499): Model->setSource('posts')
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /vagrant/data/Test/myapp/Controller/PostsController.php(29): Model->find('all')
#4 [internal function]: PostsController->index()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#6 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#8 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-05-06 01:30:28 Error: Fatal Error (1): Call to a member function link() on a non-object in [/vagrant/data/Test/myapp/View/Layouts/default.ctp, line 11]
2014-05-06 01:30:28 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /users/login/
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 11, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 11, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-06 01:32:06 Error: Fatal Error (1): Call to a member function link() on a non-object in [/vagrant/data/Test/myapp/View/Layouts/default.ctp, line 29]
2014-05-06 01:32:06 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /users/login/
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 29)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 29, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 29, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-06 01:32:47 Error: [MissingHelperException] Helper class JavascriptHelper could not be found.
Exception Attributes: array (
  'class' => 'JavascriptHelper',
  'plugin' => false,
)
Request URL: /users/login/
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(873): HelperCollection->load('Javascript', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(347): View->loadHelpers()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(1241): View->__construct(Object(UsersController))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(940): Controller->_getViewObject()
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#6 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-05-06 01:35:00 Error: [MissingHelperException] Helper class JavascriptHelper could not be found.
Exception Attributes: array (
  'class' => 'JavascriptHelper',
  'plugin' => false,
)
Request URL: /users/login/
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(873): HelperCollection->load('Javascript', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(347): View->loadHelpers()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(1241): View->__construct(Object(UsersController))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(940): Controller->_getViewObject()
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#6 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-05-06 01:35:03 Error: [MissingHelperException] Helper class JavascriptHelper could not be found.
Exception Attributes: array (
  'class' => 'JavascriptHelper',
  'plugin' => false,
)
Request URL: /users/login/
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(873): HelperCollection->load('Javascript', Array)
#1 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(347): View->loadHelpers()
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(1241): View->__construct(Object(UsersController))
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(940): Controller->_getViewObject()
#4 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#5 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#6 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-05-06 01:37:45 Error: Fatal Error (1): Call to a member function link() on a non-object in [/vagrant/data/Test/myapp/View/Layouts/default.ctp, line 29]
2014-05-06 01:37:45 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /users/login/
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 29)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 29, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 29, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-07 01:05:13 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /user/index
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-05-07 01:05:20 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /user/index
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-05-07 01:07:14 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /user/index
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-05-09 07:14:44 Error: Fatal Error (1): Call to a member function link() on a non-object in [/vagrant/data/Test/myapp/View/Layouts/default.ctp, line 30]
2014-05-09 07:14:44 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /users/login
Stack Trace:
#0 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/vagrant/data/T...', 30)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/vagrant/data/T...', 30, Array)
#2 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/vagrant/data/T...', 30, Array)
#3 /vagrant/data/Test/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-11 08:26:59 Error: [MissingControllerException] Controller class MessageController could not be found.
Exception Attributes: array (
  'class' => 'MessageController',
  'plugin' => NULL,
)
Request URL: /message/view/1
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-05-11 08:27:24 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /user/view/1
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-05-11 08:27:30 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /user/login
Stack Trace:
#0 /vagrant/data/Test/myapp/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
